spring.application.name=auth-service

# to disable DB for temporary
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



# if you need DB activte these properties

spring.datasource.url=jdbc:postgresql://dpg-d5ibul24d50c739jeke0-a.oregon-postgres.render.com:5432/userauthdatabase
spring.datasource.username=userauthdatabase_user
spring.datasource.password=k8sgQps4jmewVI6jVY5E0RObNAdYqHj7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kumareng967@gmail.com
spring.mail.password=zfehxcdgjsvkuwsk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO
logging.level.com.sukumar.task_reminder=INFO
